### ISSUE TITLE
The mod makes crafting wooden tools from non-vanilla wood planks impossible

### ISSUE THREAD

**Issue by noncom** [aparnell03/nether_expanded-1.18.2#1]
After adding this mod to Valhelsia Enhanced Vanilla 1.18 modpack I have found that all the recipes for wooden tools for BetterEnd have become unavailable for crafting. Only vanilla recipes remained.

It also worked the same way for combining it with BYG and BetterNether -- all their planks stopped working for creating wooden tools.

I am not sure what is the exact mechanism of this happening or if any other recipes do become unavailable as well. It might extend further beyond wooden tools, or it might not.

Personally, since I wanted to recenter the modpack around starting in and mostly living in the Nether and the End the problem is rather crucial for me so I did not look further.

Please fix this :) Would be cool to add Nether Expanded to the pack when this is fixed!

**Comment by aparnell03** [comment]
i think i know the issue, i'll look into it tonight and release a patch if i can. thanks!

**Comment by noncom** [comment]
Hey so I got impatient and I looked at the source and yeah I see that Nether Expanded explicitly enforces some vanilla recipes for getting some vanilla items, including wooden tools.

As I understand it redefines the recipes to remove the vanilla recipes for making the wooden stuff from Crimson and Warped woods because the mod wants to replace them with their better Crimson and Warped colored variants.

That's a nice touch! I wish all mods that introduce their wood and stones would care to provide things like this. Though BetterEnd and BetterNether do provide colored crafting tables, but not tools.. oh well, maybe they decided that too many colored tools would introduce too much clutter.

Anyway, removing the overrides fixed the situation so I just removed the corresponding folder from the jar too and it worked! Now I can choose between vanilla Wooden Axe and Nether Expanded wooden axes, which kinda breaks immersion a bit, but it's a small price to pay comparing to the previous situation.

I am not a Fabric pro so I don't know if there's a better solution to allow for granularity in deregistering certain item recipe paths. For now I'll just replace the jars on my server and client. And I'll look forward to how you'll maybe fix this in a different way.

**Comment by noncom** [comment]
Alright, I know how to fix this, here's what I did that fixed it, for example for the Wooden Axe:

1. Replace `data/minecraft/recipes/wooden_axe.json` file contents with the following:

```json
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "XX",
    "X#",
    " #"
  ],
  "key": {
    "#": {
      "item": "minecraft:stick"
    },
    "X": [
      {
        "item": "minecraft:crimson_planks"
      },
      {
        "item": "minecraft:warped_planks"
      }
    ]
  },
  "result": {
    "item": "minecraft:air"
  }
}
```

This selectively removes the Crimson and Warped recipes from vanilla.

2. Rename the file `data/minecraft/recipes/wooden_axe.json` to something with an unmatching name like `data/minecraft/recipes/no_nether_wooden_axe.json` so that it doesn't completely overwrite the the whole vanilla Wooden Axe recipe group.

3. Do that for all the involved vanilla items.

The whole idea is that setting `minecraft:air` as the recipe result effectively removes the recipe. This approach allows Nether Expanded to do what it does, without interfering with the rest of the recipes.

**Comment by noncom** [comment]
Created a pull request so that it would be easier for you. Idk if I got everything right, but I think so. Verified that it all works in the game and the targeted vanilla items are replaced with Nether Expanded variants.
